# Generated by Django 3.2.2 on 2021-07-11 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email')),
                ('nickname', models.CharField(max_length=30, verbose_name='Позывной')),
                ('slug', models.SlugField(error_messages={'unique': 'Пользователь с такой же ссылкой на профиль уже существует'}, max_length=20, unique=True, verbose_name='URL')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile_pic/', validators=[network.models.validate_image], verbose_name='Аватар')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ранг')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
                'ordering': ['experience'],
            },
        ),
        migrations.CreateModel(
            name='Snusoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Снюсоман')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Snusoman_URL')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=1000, verbose_name='Текст поста')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL поста')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_important', models.BooleanField(default=False, verbose_name='Закрепить?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тред',
                'verbose_name_plural': 'Треды',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='ThreadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('about', models.CharField(max_length=1000, verbose_name='О группе')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL группы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('followers', models.ManyToManyField(blank=True, related_name='threadgroup_followers', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='threadgroup_posts', to='network.Thread')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddField(
            model_name='thread',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.threadgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='thread_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.thread')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.rank', verbose_name='Ранг'),
        ),
        migrations.AddField(
            model_name='user',
            name='snusoman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.snusoman', verbose_name='Какой вы снюсоед?'),
        ),
    ]
