# Generated by Django 3.2.2 on 2021-05-30 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('test', models.CharField(default='123', max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile_pic/', validators=[network.models.validate_image], verbose_name='Аватар')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким логином уже сущесвует'}, max_length=30, unique=True, verbose_name='Логин')),
                ('nickname', models.CharField(max_length=30, validators=[network.models.validate_nickname], verbose_name='Позывной')),
                ('slug', models.SlugField(error_messages={'unique': 'Пользователь с такой же ссылкой на профиль уже существует'}, max_length=20, unique=True, verbose_name='URL')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('friends', models.ManyToManyField(blank=True, to='network.Profile')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ранг')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ранг',
                'verbose_name_plural': 'Ранги',
                'ordering': ['experience'],
            },
        ),
        migrations.CreateModel(
            name='Snusoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Снюсоман')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Snusoman_URL')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=1000, verbose_name='Текст поста')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL поста')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_important', models.BooleanField(default=False, verbose_name='Закрепить?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.profile', verbose_name='Автор')),
                ('likes', models.ManyToManyField(related_name='thread_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тред',
                'verbose_name_plural': 'Треды',
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.rank', verbose_name='Ранг'),
        ),
        migrations.AddField(
            model_name='profile',
            name='snusoman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.snusoman', verbose_name='Какой вы снюсоед?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(error_messages={'unique': 'Уже существует'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='network.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='network.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='Комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.thread')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-time_create'],
            },
        ),
    ]
