# Generated by Django 3.2.2 on 2021-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.SlugField(max_length=20, unique=True, verbose_name='URL'),
        ),
    ]
