# Generated by Django 3.2.2 on 2021-07-12 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=1000, verbose_name='Текст поста')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL поста')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_important', models.BooleanField(default=False, verbose_name='Закрепить?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тред',
                'verbose_name_plural': 'Треды',
                'ordering': ['-time_create'],
            },
        ),
        migrations.CreateModel(
            name='PostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('about', models.CharField(max_length=1000, verbose_name='О группе')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL группы')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('followers', models.ManyToManyField(blank=True, related_name='postgroup_followers', to=settings.AUTH_USER_MODEL)),
                ('posts', models.ManyToManyField(blank=True, related_name='postgroup_posts', to='network.Post')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.RemoveField(
            model_name='threadgroup',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='threadgroup',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thread',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.DeleteModel(
            name='ThreadGroup',
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.postgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.post'),
            preserve_default=False,
        ),
    ]
