# Generated by Django 3.2.2 on 2021-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=500, null=True, verbose_name='О себе'),
        ),
    ]
