# Generated by Django 3.2.2 on 2021-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210615_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=30, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
