# Generated by Django 3.2.2 on 2021-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=500, verbose_name='О себе'),
        ),
    ]
