# Generated by Django 3.2.2 on 2021-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210712_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, to='network.Group'),
        ),
    ]
