# Generated by Django 3.2.2 on 2021-05-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210513_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snusoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Снюсоман')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Snusoman_URL')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pic/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='snusoman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='network.snusoman', verbose_name='Снюсоман'),
        ),
    ]
