# Generated by Django 3.2.2 on 2021-07-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
    ]
