# Generated by Django 3.2.2 on 2021-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210516_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
