# Generated by Django 3.2.2 on 2021-07-12 17:19

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='images/background_photo', validators=[network.models.validate_image], verbose_name='Фон группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_avatar',
            field=models.ImageField(blank=True, upload_to='images/group_avatar/', validators=[network.models.validate_image], verbose_name='Аватар группы'),
        ),
    ]
