# Generated by Django 3.2.2 on 2021-07-14 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210712_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='group',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='images/background_photo/', validators=[network.models.validate_image], verbose_name='Фон группы'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_from_user', to=settings.AUTH_USER_MODEL, verbose_name='От пользователя')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_to_user', to=settings.AUTH_USER_MODEL, verbose_name='К пользователю')),
            ],
        ),
    ]
