# Generated by Django 3.2.2 on 2021-07-26 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210714_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Запросы в друзья', 'verbose_name_plural': 'Запросы в друзья'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['title'], 'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_important', '-time_create'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='background_photo',
            field=models.ImageField(blank=True, upload_to='images/background_photo/', validators=[network.models.validate_image], verbose_name='Фон сообщества'),
        ),
        migrations.AlterField(
            model_name='group',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='postgroup_followers', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_avatar',
            field=models.ImageField(blank=True, upload_to='images/group_avatar/', validators=[network.models.validate_image], verbose_name='Аватар сообщества'),
        ),
        migrations.AlterField(
            model_name='group',
            name='moderator',
            field=models.ManyToManyField(blank=True, related_name='group_moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='postgroup_posts', to='network.Post', verbose_name='Посты'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL сообщества'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название сообщества'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=40000, verbose_name='Текст поста'),
        ),
    ]
