# Generated by Django 3.2.2 on 2021-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20210516_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(max_length=32, null=True, verbose_name='Пароль'),
        ),
    ]
