# Generated by Django 3.2.2 on 2021-05-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
