# Generated by Django 3.2.2 on 2021-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20210821_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='unique_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Уникальный id'),
        ),
    ]
