# Generated by Django 3.2.2 on 2021-05-25 06:56

from django.conf import settings
from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0015_auto_20210519_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(related_name='thread_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'Анонимный пользователь с таким логином уже существует'}, max_length=30, null=True, validators=[network.models.validate_nickname], verbose_name='Позывной'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Пользователь с такой же ссылкой на профиль уже существует'}, max_length=20, unique=True, verbose_name='URL'),
        ),
    ]
