# Generated by Django 3.2.2 on 2021-05-25 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0017_auto_20210525_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, null=True, verbose_name='Ответ на комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата ответа')),
                ('time_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.profile')),
                ('for_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.comment')),
                ('likes', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ответ на комментарий',
                'verbose_name_plural': 'Ответы на комментарии',
                'ordering': ['time_create'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.reply'),
        ),
    ]
