# Generated by Django 3.2.2 on 2021-08-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_post_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unique_id',
        ),
    ]
