# Generated by Django 3.2.2 on 2021-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_post_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unique_key',
        ),
        migrations.AddField(
            model_name='post',
            name='unique_id',
            field=models.CharField(max_length=6, null=True, unique=True, verbose_name='Уникальный id'),
        ),
    ]
