# Generated by Django 3.2.2 on 2021-08-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20210821_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='snusoman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='network.snusoman', verbose_name='Какой вы снюсоед?'),
        ),
    ]
