# Generated by Django 3.2.2 on 2021-09-01 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-time_create'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты'},
        ),
        migrations.AlterModelOptions(
            name='messagebody',
            options={'ordering': ['-time_send'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='messagebody',
            name='time_send',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время когда было отправлено сообщение'),
            preserve_default=False,
        ),
    ]
