# Generated by Django 3.2.2 on 2021-09-05 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_auto_20210901_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_user1', to='network.user', verbose_name='Пользователи чата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chat_user2', to='network.user', verbose_name='Пользователи чата'),
            preserve_default=False,
        ),
    ]
