# Generated by Django 3.2.2 on 2021-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210905_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagebody',
            options={'ordering': ['time_send'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Chat# <django.db.models.fields.CharField>', max_length=255, verbose_name='Название чата'),
        ),
    ]
