# Generated by Django 3.2.2 on 2021-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210905_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_group_chat',
        ),
        migrations.AlterField(
            model_name='chat',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания чата'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название чата'),
        ),
    ]
